language: objective-c

osx_image: xcode7.1
xcode_sdk: iphonesimulator9.1

before_install:
    - brew update
    - brew uninstall xctool && brew install --HEAD xctool
install: travis_wait 30 pod install

xcode_workspace: Signal.xcworkspace
xcode_scheme: Signal
